### ISSUE TITLE
sd mount failed!

### ISSUE THREAD

**Issue by agentxxxxxx** [AidanHockey5/STM32_VGM_Player_YM2612_SN76489#5]
oled displays SD MOUNT FAILED!. I had checked all of the sd slot connetions and they are ok. what else should I check?

**Comment by AidanHockey5** [comment]
Hello!

An SD card failing to mount could be for a number of reasons.

Have you made sure that the SD card is formatted as FAT32?

Are your VGM files uncompressed? (You can’t use VGZ files, you have to extract the VGM inside of them)

Are the pins inside of your SD socket in good condition?

Did you build this as a breadboard prototype? Some cheap SD card adapters are not designed properly and will never mount correctly.

Have you just recently programmed your board? If so, unplug the board from power, then plug the board back in. SD cards almost never mount after a programming cycle. Make sure your jumpers on the STM32 board are both in the down position so you don’t go to the boot loader.

**Comment by agentxxxxxx** [comment]
thanks for your supports! I had solved it. I wired the sd card pin directly to the stm32 board and it worked. the SD slot might be broken internal. 

Thanks for your excellent project! It's wonderful!!
