### ISSUE TITLE
Standalone flasher not working

### ISSUE THREAD

**Issue by CornBrown** [AidanHockey5/STM32_VGM_Player_YM2612_SN76489#7]
The error i get is that there are python files missing in c:\users\aiden\....    and wont run    (windows 7 64bit)    Everything is working in win10

**Comment by AidanHockey5** [comment]
Hello,

Windows 7 has reached its end of life (EoL) and is therefore unsupported.

I could not recreate your issue on Windows 10. I spooled up a fresh Windows 10 VM with a username that is not "Aidan" and I managed to flash the firmware just fine.
* Make sure the board is receiving 12V and is powered on. 
* Make sure that you've got the CH340 drivers installed. You can download them here:
https://cdn.sparkfun.com/assets/learn_tutorials/8/4/4/CH341SER.EXE
* Make sure your left jumper is in the UP position on your blue pill microcontroller board.
https://www.aidanlawrence.com/wp-content/uploads/2021/01/mb_jumper-scaled.jpg
* Make sure you press the RESET button before invoking the programmer.

>Everything is working in win10

Looks like that's the answer. Windows 7 is simply unsupported. You might be able to run the flashing script in Windows 7 via Python. View the README.txt file that's included with the standalone and run Flash.py
