### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by 6502bender** [AidanHockey5/STM32_VGM_Player_YM2612_SN76489#9]
Hello
After upgrading mega blaster to v3.0, there were problems with SN76489. PSG began to sound terrible, extraneous sounds appear and the frequency seems to be floating
Here is a link to a video for an example. https://youtu.be/bkRAT_hYAm4
There is no such problem in version 2.0.
YM on the contrary, began to sound much better.
thank.

**Comment by AidanHockey5** [comment]
Your issue has been replicated. There is something wrong with the way that I'm writing to the PSG. I'll see if I can find a solution.

**Comment by AidanHockey5** [comment]
Unable to verify on the official Mega Blaster board. The PSG works just fine. I previously thought there might have been an issue, but I noticed that my PSG MUTE switch was set.

Sadly, since your board is hand-made, I won't be able to help you much. I would try and verify your hardware against the original schematic. Make sure the PSG's WE pin is connected to pin PB5.

**Comment by 6502bender** [comment]
the fact is that if I upload the firmware v2.0, then PSG sounds as expected.

2021-02-25 20:07 GMT+03:00, Aidan Lawrence <notifications@github.com>:

**Comment by jareklupinski** [comment]
that's a wild board!
![Screen Shot 2021-02-25 at 3 21 10 PM](https://user-images.githubusercontent.com/2049284/109212165-2dec2480-777d-11eb-96df-1e22f438201e.png)
rly the only diff in the sn-specific code is the amount of microseconds btwn writes, maybe on a hand-spun board this 3uS difference is the factor?
I'm finding the PSG loves taking almost the entire sample to clock its data bus :(

**Comment by 6502bender** [comment]
Thank you, so I will dig towards SN76489, but that will be later.

Now I started another experiment, it might be interesting.

https://youtu.be/YdA0xXXmrXM

The bottom line is to use the YMF276-M synthesizer

The YMF276-M was used in FM Towns II computers, and is kind of a lower power version of the YM3438.

The main feature of this chip (for me) is that it requires an external DAC (using the I2S interface). Therefore, the DAC with a preamplifier can be maximally isolated from the digital part, thereby seriously reducing digital noise, pickup, etc. in the sound.

The DAC used the BU9480F.

Next, I want to screw this chip to my console.
